### ISSUE TITLE
Re-examine Slack integration method

### ISSUE THREAD

**Issue by ashmastaflash** [cloudpassage/cortex#41]
See if there's a more reliable abstraction in the Slack SDK than the RTM web socket.

**Comment by ashmastaflash** [comment]
@eatwithforks 👀

**Comment by eatwithforks** [comment]
+1

**Comment by ashmastaflash** [comment]
When the Slack connection dies, this is the stack trace:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/runner.py", line 161, in slack_in_manager
    for message in slack:
  File "/app/donlib/slack.py", line 40, in __iter__
    messages = self.client.rtm_read()
  File "/usr/local/lib/python2.7/dist-packages/slackclient/_client.py", line 120, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/usr/local/lib/python2.7/dist-packages/slackclient/_server.py", line 138, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 300, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 317, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 330, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 364, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 434, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_socket.py", line 94, in recv
    "Connection is already closed.")
WebSocketConnectionClosedException: Connection is already closed.
```

**Comment by ashmastaflash** [comment]
Auto-reconnect (which should resolve this issue) is available in Slack client 1.2.0: https://github.com/slackapi/python-slackclient/issues/118

Need to re-pin `slackclient` in requirements.txt to 1.2.0 or greater and change `self.client.rtm_connect() `to `self.client.rtm_connect(auto_reconnect=True)` in app/donlib/slack.py

**Comment by ashmastaflash** [comment]
Tested this branch for 48 hours, no Slack thread failures.  Another environment, running code without this fix, experienced one Slack thread failure.

**Comment by ashmastaflash** [comment]
Done
